### ISSUE TITLE
Types are not generated on the first run. No such file or directory

### ISSUE THREAD

**Issue by Leo5878** [JasonShin/sqlx-ts#111]
I am running sqlx-ts for the first time; the type file does not exist yet, and the types are being generated.
The file already exists, and the types need to be updated. After running the command "command", the file is deleted, and an error occurs:

```sh
$ sqlx-ts ./src/model/ -g --config .sqlxrc.json --generate-path ./src/model/types.ts
[INFO] Scanning "./src/model/" for SQLs with extension Ts
thread 'main' panicked at src/parser/mod.rs:133:45:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error Command failed with exit code 101.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 101
```

But on re-running the command, the file is created again, and the types are generated again.

**Comment by JasonShin** [comment]
Thanks for reporting, that is strange - I will take a look soon. Can you try without `--generate-path` in the meantime?

**Comment by Leo5878** [comment]
Unfortunately, i can't(

**Comment by JasonShin** [comment]
@Leo5878 hello, I'm trying to reproduce this issue.

I am trying multiple ways to run sqlx-ts based on your explanations
- for `generate-path`, when I give it a file path that does not exist yet (for example `./tests/stagingz/hello.types.ts`). I can see it correctly creates the non-existing folder and the type definition under the folder as well.
- I am only seeing the same error in the issue if I provide a wrong `path to typescript or javascript project`
<img width="988" alt="Screen Shot 2024-06-10 at 11 18 30 am" src="https://github.com/JasonShin/sqlx-ts/assets/2525002/32db6907-8d3a-4352-b94d-1e4b81949bea">
^^^ in this example, I am intentionally providing `./tests/stagingz` which does not exist

**Comment by JasonShin** [comment]
This is now released as 0.12.1 https://github.com/JasonShin/sqlx-ts/releases/tag/v0.12.1

**Comment by Leo5878** [comment]
@JasonShin Hi! No, that's not quite right. According to my tests, the level of nesting somehow affects this issue. I couldn't understand why, but during debugging, I noticed that  [scanfolder](https://github.com/JasonShin/sqlx-ts/blob/217d5b1d0ff73fe5c98d4790c78f4615d85e6f0f/src/main.rs#L51) returns the file specified in generate-path, not all the files with the .ts extension in the folder. After running it again, it returns all the files. Somehow, my PR managed to fix this problem. I will try to study the issue further in the future if I have the opportunity.

Thank you for accepting my PR!

**Comment by JasonShin** [comment]
Thanks, I have added my thought in https://github.com/JasonShin/sqlx-ts/pull/114, thanks for this
