### ISSUE TITLE
Support for RETURNING *

### ISSUE THREAD

**Issue by simplenotezy** [JasonShin/sqlx-ts#117]
It would be nice if the generator supported `RETURNING *` in queries, like:

https://jasonshin.github.io/sqlx-ts/reference-guide/4.2.INSERT.html

```diff
const fetchAnalysisId = await this.db.query({
  text: sql`
  INSERT INTO analysis (type, status) VALUES ($1, $2)
+  RETURNING id
  `,
  values: [AnalysisType.EMAIL, AnalysisStatus.PENDING],
});
```

**Comment by JasonShin** [comment]
That's a great suggestion

**Comment by JasonShin** [comment]
This PR should handle this https://github.com/JasonShin/sqlx-ts/pull/121

**Comment by JasonShin** [comment]
This is now supported in v0.14.0 👍

**Comment by simplenotezy** [comment]
Wow amazing. That was quick. Will update asap and check it out
