### ISSUE TITLE
Process .sql files

### ISSUE THREAD

**Issue by JasonShin** [JasonShin/sqlx-ts#13]
As part of sqlx-ts, it would be great to support the pattern where users can write SQLs in .sql files. It will allow a pattern for the users where they can write SQLs in .sql files, process them as part of the sqlx-ts SQL compile time check.

**Comment by nicoabie** [comment]
is there an ETA por this feature?

**Comment by JasonShin** [comment]
@nicoabie hello, I'm currently on a holiday so I'm thinking I can do it around next month. There will be some rules around handling .sql files for example providing @name annotation will be mandatory

**Comment by JasonShin** [comment]
The issue is moved to the notion board https://foil-adasaurus-bba.notion.site/f1ca150c5b0141d69eaf136c596ae649?v=efc6af2aa3174f87a39bec8edc09c4a9
