### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by JasonShin** [JasonShin/sqlx-ts#4]
The aim of supporting SQLite is to make sqlx-ts to be truly a database-agnostic tool that anyone in any situation can take an advantage of it.

For SQLite support, we should provide the following

- A new database type, SQLite as part of CLI arg and environment
- For now, we should only support [On-Disk variant](https://www.sqlite.org/inmemorydb.html) of SQLite as SQLite is a tool that lives outside of your main application and does not share the connection with your inline code. If you have a brilliant idea to support SQLite in sqlx-ts, please let me know
- The main functionality of sqlx-ts should be supported: checking raw SQLs in compile-time
- By the time you pick this issue up, we might have support for `.sql` file check. If so, please also support `.sql` files as part of SQLite integration
- Add [end-to-end tests](https://github.com/JasonShin/sqlx-ts/tree/main/tests). Add both happy path and failure path

**Comment by JasonShin** [comment]
I want sqlx-ts to focus on MySQL and Postgres

**Comment by PorcoRosso85** [comment]
Doesn't a timeline already exist that supports sqlite?
