### ISSUE TITLE
Issue when using alias for table in mysql (verbose field name generated)

### ISSUE THREAD

**Issue by nicoabie** [JasonShin/sqlx-ts#69]
```typescript
import { sql } from "sqlx-ts";

const pepe = sql`
-- @name: allUsers 
select firstName, cc.companyName from user u join centralized_company cc on u.centralizedCompanyId = cc.centralizedCompanyId`

```

generates

```typescript
export type AllUsersParams = [];


export interface IAllUsersResult {
    centralizedCompanyCompanyName: string; // <- wrong
	firstName: string;
};


export interface IAllUsersQuery {
    params: AllUsersParams;
    result: IAllUsersResult;
};

```

and it should generate

```typescript
export type AllUsersParams = [];


export interface IAllUsersResult {
    companyName: string; // <- right
	firstName: string;
};


export interface IAllUsersQuery {
    params: AllUsersParams;
    result: IAllUsersResult;
};
```

**Comment by JasonShin** [comment]
Hello, thank you for reporting this concern. When it comes to picking the right name to use when generating a type, especially for a JOIN query, the initial design is to pick the least conflict-free naming choice as possible. Hence, I can see that the default name choice of the joined table's field by sqlx-ts sounds a bit verbose.

To overcome this, please try out aliasing your field name in your query.

```
const pepe = sql`
-- @name: allUsers 
select firstName, cc.companyName as companyName
from user u
join centralized_company cc on u.centralizedCompanyId = cc.centralizedCompanyId`
```

**Comment by nicoabie** [comment]
Thanks for the feedback but please note that if a user does not explicitely set an alias like `as companyName` the result of the query would be companyName instead of `centralizedCompanyCompanyName` and the type for it will be wrong.

When sqlx-ts creates `centralizedCompanyCompanyName: string` is giving bad hints

<img width="995" alt="image" src="https://github.com/JasonShin/sqlx-ts/assets/2797992/85fd47f6-4df3-4b61-9e6b-2685e85f261e">

**Comment by JasonShin** [comment]
@nicoabie understood, I will think about this a bit more, an option is to always raise warnings when a JOIN query is provided to sqlx-ts but it does not have an alias -> in this scenario, sqlx-ts will try its best to come up with a naming choice that does not lead to naming-conflict (aka TS build error)

**Comment by nicoabie** [comment]
this is the case you are thinking right?

<img width="639" alt="image" src="https://github.com/JasonShin/sqlx-ts/assets/2797992/a7968c2d-fb57-4fec-b7a5-69d2a4579e32">

I think in that case when doing the query one column will override the other. 

What I would do is when generating the type if two columns get the same output trigger a compilation error.

**Comment by JasonShin** [comment]
Compilation error is definitely an option, I'm so far I'm leaning toward having sqlx-ts to raise warnings for minor releases and errors in the major releases. I can queue it up in the TODO list of v1.0.0

**Comment by JasonShin** [comment]
https://github.com/JasonShin/sqlx-ts/pull/71 Hello, I got a time to patch this - will release this soon
