### ISSUE TITLE
Support for decorators?

### ISSUE THREAD

**Issue by simplenotezy** [JasonShin/sqlx-ts#76]
First of all, thanks for a really great contribution with this package. After trying out the power it brings from Rust, I am thrilled to see support for this in Typescript. This will be huge.

I am currently trying to set it up in a rather large project built in Nest.js, however I am facing some initial issues getting started. I am getting error:

```bash
❯ npx sqlx-ts src/ --db-host=127.0.0.1 --db-port=26257 --db-type=postgres --db-user=root

[INFO] Scanning "src/" for SQLs with extension Ts
error: Expression expected
 --> <src/statistics/api/statistics.api.module.ts>:7:1
  |
7 | @Module({
  | ^

thread 'main' panicked at 'failed to parse module: ()', src/parser/mod.rs:261:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by JasonShin** [comment]
thanks, that's strange, I can double check this tonight

**Comment by simplenotezy** [comment]
Sounds good @JasonShin - let me know if I can help!

**Comment by JasonShin** [comment]
👍 @simplenotezy very easy fix https://github.com/JasonShin/sqlx-ts/pull/78 I just had to allow decorators in SWC compiler config haha...

**Comment by simplenotezy** [comment]
nice @JasonShin - looking forward testing it out, and for sure, will let you know how it goes integrating
