### ISSUE TITLE
Support for search path options for PosgreSQL.

### ISSUE THREAD

**Issue by Louis-Amas** [JasonShin/sqlx-ts#89]
Everything is in the title.

Currently, I'm unable to use this tool without this functionality as my table are stored in schemas :(

**Comment by JasonShin** [comment]
@Louis-Amas hello thanks for this, I will get on to this really soon

**Comment by JasonShin** [comment]
Hello @Louis-Amas, I'm thinking I will add the following support

For validating queries
- By default, it will use the current user session's default search path
- Will expose an optional `schema` config (currently it's only assuming the schema name is `public` 😭 )

For type generations
- If you need to reference another schema, prefer using the fully qualified schema names in your queries

Could you let me know why we'd need to expose search path option?

**Comment by JasonShin** [comment]
Hello, this is now supported in v0.10.0! https://github.com/JasonShin/sqlx-ts/releases/tag/v0.10.0
